### ISSUE TITLE
website not displaying correctly or properly?

### ISSUE THREAD

**Issue by 1234987635** [binlist/binlist-data#144] opened 2017-05-01 14:47 UTC
Binlist.net

Enter the first digits of a card number (BIN/IIN)

Scheme / network

Visa

Brand

Visa/Dankort

Card number

Length

16

LUHN
Yes / 
No

Type
Debit / 
Credit

Prepaid
Yes / 
No

Country
🇩🇰 Denmark

(latitude: 56, longitude: 10)

Bank
Jyske Bank, Hjørring

www.jyskebank.dk

+4589893300

API

curl / https
curl -H "Accept-Version: 3" "https://lookup.binlist.net/45717360"

{
  "number": {
    "length": 16,
    "luhn": true
  },
  "scheme": "visa",
  "type": "debit",
  "brand": "Visa/Dankort",
  "prepaid": false,
  "country": {
    "numeric": "208",
    "alpha2": "DK",
    "name": "Denmark",
    "emoji": "🇩🇰",
    "currency": "DKK",
    "latitude": 56,
    "longitude": 10
  },
  "bank": {
    "name": "Jyske Bank",
    "url": "www.jyskebank.dk",
    "phone": "+4589893300",
    "city": "Hjørring"
  }
}

Node.js / npm / browser(ify)
npm install binlookup

var lookup = require('binlookup')()

// callback
lookup('45717360', function( err, data ){
  if (err)
    return console.error(err)

  console.log(data)
})

// promise
lookup('45717360').then(console.log, console.error)

•npm package
•Source code

**Comment by tjconcept** [comment] 2017-05-02 06:49
Hi @1234987635 (nice account name by the way 😐)

It looks like you have copied the entire content of the site, but from that, I do not see what the problem is?

The website is supposed to look like this:
![screen shot 2017-05-02 at 08 48 39](https://cloud.githubusercontent.com/assets/801895/25606904/2ec5fdbe-2f14-11e7-9658-cca0fa6f16e9.png)

**Comment by 1234987635** [comment] 2017-05-02 12:59
New format that doesn’t seem to work?  You put in a number and it defaults back to this?

Binlist.net
Top of Form
Enter the first digits of a card number (BIN/IIN)
Bottom of Form

  *   Scheme / network
Visa

  *   Brand
Visa/Dankort

  *   Card number
     *   Length
16

     *   LUHN

        *   Yes
        *   No
  *   Type

     *   Debit
     *   Credit
  *   Prepaid

     *   Yes
     *   No
  *   Country
🇩🇰 Denmark
(latitude: 56, longitude: 10)



Ben Minor
Disney Store North America
Loss Prevention Supervisor
Office: (901) 433-2021
Email: ben.minor@disney.com<mailto:ben.minor@disney.com>

**Comment by tjconcept** [comment] 2017-05-02 15:00
Hi Ben,

That's not the default, but the result of a search for "4571 7360".

Which BIN are you looking up? Which browser are you using?

**Comment by 1234987635** [comment] 2017-05-02 15:09
415231  bin

https://binlist.net/

The previous version on that link looked completely different.  When I put in the above bin number you can’t “enter” or anything to get the info?


Ben Minor
Disney Store North America
Loss Prevention Supervisor
Office: (901) 433-2021
Email: ben.minor@disney.com<mailto:ben.minor@disney.com>

**Comment by tjconcept** [comment] 2017-05-02 15:28
Hi Ben,

When putting in that particular BIN, I'm seeing the following:

![screen shot 2017-05-02 at 17 28 06](https://cloud.githubusercontent.com/assets/801895/25625429/c625c110-2f5c-11e7-8169-65cff210c947.png)

Do you know which OS and browser version you are using? This might be a browser support related issue.

**Comment by Jimvin** [comment] 2017-05-02 15:47
Could it be that you have JavaScript disabled? The result updates as you
type, so if you're not allowing JavaScript your experience may differ from
the expected behaviour.

Jim

**Comment by tjconcept** [comment] 2017-05-02 15:55
Thanks Jim, that's a very probable cause.

**Comment by 1234987635** [comment] 2017-05-02 16:12
I am using IE11.  Some of my co-workers have the same issue as I do (not allowing “entering”) to get the new country but one co-worker gets what you show you get?  It worked fine for me last week with the old display format.


Ben Minor
Disney Store North America
Loss Prevention Supervisor
Office: (901) 433-2021
Email: ben.minor@disney.com<mailto:ben.minor@disney.com>

**Comment by tjconcept** [comment] 2017-05-02 21:04
So, admittedly I did not initially do any cross-browser testing, and indeed the problem seems to be IE not having the object `object.assign` method.

I've now patched it with a polyfill (https://github.com/binlist/www/commit/0a77ffb93cd4b2ebc88ad084798e828978d79981).

Please give it another shot, Jim. You might have to press <kbd>CTRL</kbd>  + <kbd>R</kbd> to give the browser a proper reload first.

It should be noted that you need the very latest version of Internet Explorer (11) as earlier ones does not have the `element.dataset` method that I'm also using. It is not something I intend to fix as a browser upgrade would be recommended in any such case.

**Comment by tjconcept** [comment] 2017-05-04 15:26
I'm going to close this for now, but feel free to reopen if the issue persists.

**Closed as completed by tjconcept** 2017-05-04 15:26 UTC

**Comment by 1234987635** [comment] 2017-05-04 16:58
That’s fine, it never got resolved for me and I kind of doubt it will at this point.  Thanks anyway.  Why did you change the format anyway?  Just curious.


Ben Minor
Disney Store North America
Loss Prevention Supervisor
Office: (901) 433-2021
Email: ben.minor@disney.com<mailto:ben.minor@disney.com>

**Comment by tjconcept** [comment] 2017-05-04 17:12
Hi Ben,

If we can locate the issue, we can surely get it working. Did you try refreshing the browser with the mentioned key combination?

We changed the format to allow for more data in there.

**Comment by 1234987635** [comment] 2017-05-04 20:45
I tried the Ctrl + R   and it kind of works if you do it each time.  I’ll just use another site that’s not as efficient as your old one used to be ☺.   Thanks for your efforts though.


Ben Minor
Disney Store North America
Loss Prevention Supervisor
Office: (901) 433-2021
Email: ben.minor@disney.com<mailto:ben.minor@disney.com>
